### ISSUE TITLE
About Computing Platform

### ISSUE THREAD

**Issue by MrPicklesGG** [Kin-Zhang/mmfn#10]
感谢大佬的工作！

请问您实验使用的GPU型号以及数据采集和训练的耗时，想做一下参考。

**Comment by Kin-Zhang** [comment]
数据采集 如果是short+tiny+long 大概1个3090开四个CARLA 24小时左右（具体这个我还真没计算过而且数据收集我没上传记录log啥的）

---

训练时间，设备【8块3090】，系统版本等详细信息如下 [13小时左右]：
![image](https://github.com/Kin-Zhang/mmfn/assets/35365764/9f084203-8796-4f34-97b6-00431f6e8b9b)
