### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by ms-kumar** [Kin-Zhang/mmfn#11]
Thanks for the  great work, may I know how to download pretrained model and can run eval (at [wandb.ai](https://github.com/Kin-Zhang/mmfn/blob/main/wandb.ai) not showing any info)?

**Comment by Kin-Zhang** [comment]
I fully recommend if you want to do the baseline experiment, collect the same data as you want and eval under the same cases. More discussion on this discussion: https://github.com/Kin-Zhang/carla-expert/discussions/4

**Comment by Kin-Zhang** [comment]
Hi based on other requests, I decided to open pretrained for all you to test, here is [download link](https://hkustconnect-my.sharepoint.com/:f:/g/personal/qzhangcb_connect_ust_hk/EvMM_DMzBppNvC_Scew4-SgB4RWvI-uebxZ1AiIgng9a5g). Related issue: https://github.com/Kin-Zhang/mmfn/issues/14
