### ISSUE TITLE
Could you provide a trained model img?

### ISSUE THREAD

**Issue by wutianze** [Kin-Zhang/mmfn#14]
Thank you for the great work!
I want to try running mmfn, could you please provide a trained model img for us to download?  Also, I am not sure if I can skip the data&train steps to run eval step directly. Could you help me with this?

**Comment by nGQD** [comment]
@Kin-Zhang Thanks for the excellent work! 
It would be great if we could have a directly deployable pre-trained model for extension work or experiments.

**Comment by Kin-Zhang** [comment]
Yes, I can. But if you are for a comparison experiment I will suggest collecting the same dataset and trained otherwise it's not a fair comparison.

But if you only for deployable I can try to find a model pretrained weight for you to test. But maybe it's not the one in paper experiment table... Is that fine?

**Comment by wutianze** [comment]
> Yes, I can. But if you are for a comparison experiment I will suggest collecting the same dataset and trained otherwise it's not a fair comparison.
> 
> But if you only for deployable I can try to find a model pretrained weight for you to test. But maybe it's not the one in paper experiment table... Is that fine?

Yes, please.

**Comment by Kin-Zhang** [comment]
Hi all,

check here to download pretrained weight, I tested `mmfn_vec` one on my desktop. Hopefully other two works also. [download link](https://hkustconnect-my.sharepoint.com/:f:/g/personal/qzhangcb_connect_ust_hk/EvMM_DMzBppNvC_Scew4-SgB4RWvI-uebxZ1AiIgng9a5g)

And also update the README part for you to easily setup. (hopefully
