### ISSUE TITLE
Training Data Towns

### ISSUE THREAD

**Issue by Kshitizbansal** [Kin-Zhang/mmfn#15]
Hi,

Could you please specify which towns were used to train the model? The train.yaml file has all the towns commented out except for "Town03". Does this mean that only Town03 data was used to generate the results specified in the paper? It would be great if you could specify the final training and validation town used in the paper. 

Also the paper mentions 207k frames were used for training. Are these from all 8 CARLA towns? When we ran the data collection script we got lesser data collected (~182k frame).  

Your response would be appreciated.

Thanks.

**Comment by Kin-Zhang** [comment]
the paper is trained in short and tiny Town01-Town10, adding additional long for other towns [1,2,3,6] except val towns.
So I think maybe you need to add `long` in the code by uncomment:
https://github.com/Kin-Zhang/mmfn/blob/main/team_code/mmfn_utils/datasets/config.py#L83-L84

this config is all the same as other methods in the paper which means we trained them all in the same amount of dataset for fair comparison.

**Comment by Kin-Zhang** [comment]
btw, `Maybe I will recommend you collect short and long routes for the dataset. Maybe 100K is enough to train a fine-fine mmfn e2e agent.` 

https://github.com/Kin-Zhang/mmfn/issues/12#issuecomment-1775872117

**Comment by Kshitizbansal** [comment]
Thanks for your prompt response. Could you also let me know what routes did you use for evaluation?

Regards,
Kshitiz

**Comment by Kin-Zhang** [comment]
Here is the route for evaluation: https://github.com/Kin-Zhang/mmfn/blob/main/leaderboard/data/evaluation_routes/routes_eval_NEAT.xml

and also mentioned in the [paper](https://arxiv.org/abs/2207.00186):
![image](https://github.com/Kin-Zhang/mmfn/assets/35365764/e29032f4-b3f9-46e2-b0ab-fda0c9c5c676)
