### ISSUE TITLE
采集数据出现问题

### ISSUE THREAD

**Issue by heyoupeng819** [Kin-Zhang/mmfn#16]
您好，我按照您提供的教程配置了项目运行环境，当我运行phase0_run_eval.py时，出现了以下错误，我尝试为该文件加上可执行权限但并没有解决这个问题。请问该如何解决呢？
Disabling core dumps.
 =======> input is a folder, start with for loop 
--------------------TEST Agent: auto_pilot.py--------------------
Contiune the route from file: /home/gaoshu/RLmodels/mmfn/data/results/routes_town03_tiny_auto_pilot.json

========= Preparing RouteScenario_31 (repetition 0) =========
> Setting up the agent
Data save path /home/gaoshu/RLmodels/mmfn/data/nss_1114/Town03_tiny/Town03_31_11_14_12_45_28
> Loading the world
> Running the route
Loading success for map, save path is: /home/gaoshu/RLmodels/mmfn/data/nss_1114/Town03_tiny/Town03_31_11_14_12_45_28
start to build rmap. map_number: 1
  0%|                                                                                                                                                                                   | 0/1 [00:00<?, ?it/s]/home/gaoshu/RLmodels/mmfn/assets/package/rough_map_node /home/gaoshu/RLmodels/mmfn/data/nss_1114/Town03_tiny/Town03_31_11_14_12_45_28/opendrive
/bin/sh: 1: /home/gaoshu/RLmodels/mmfn/assets/package/rough_map_node: Permission denied

Stopping the route, the agent has crashed:
> list index out of range

leaderboard.autoagents.agent_wrapper.AgentError: list index out of range
> Stopping the route

========= Results of RouteScenario_0 (repetition 0) ------ FAILURE =========

**Comment by Kin-Zhang** [comment]
可否再检查一遍缺陷 在 assets/package 目录下运行 ll 截个图？

注意权限需要给 +wx
```
chmod +wx assets/package/*
```

**Comment by heyoupeng819** [comment]
没有明白第一句话什么意思，scripts文件夹已经添加过可执行权限了。我的电脑系统是ubuntu20.04，我看您的项目里面提供了三个rough_map_node文件，我具体的做法是在package下创建了一个rough_map_node文件夹，然后执行了setup_lib.sh 然后就该文件夹生成了一个rough_map_node_20的文件。请问这个文件有什么作用？我在运行项目时好像是因为这个文件导致出现的错误。

**Comment by Kin-Zhang** [comment]
抱歉 说错了 应该是package下的 给可写和可运行 如下，根据你的提示 我重新直接写进了 setup_lib.sh 文件里 如果可以的话 你也可以再运行一遍就ok了~

```
chmod +wx assets/package/*
```

paper里的mmfn_vectornet 需要此node来进行解析opendrive格式的map

**Comment by heyoupeng819** [comment]
好的，我设置后成功能采集数据了，非常感谢您的指导！

**Comment by Kin-Zhang** [comment]
另外 根据其他人的请求，我也上传了 我能找到的一些pretrained weight供大家测试 （可以看一下update commit），当然最好还是自己收一遍数据 将自己的方法和baseline在同一数据下训练，对比会绝对公平。

有其他问题，欢迎再告知我。
