### ISSUE TITLE
Python 3.8, CARLA 0.9.14, Leaderboard 2.0

### ISSUE THREAD

**Issue by abol-karimi** [Kin-Zhang/mmfn#17]
I want to test the trained agent in CARLA 0.9.14. How should I go about it? Do you have any plans to upgrade to Leaderboard 2.0?

**Comment by Kin-Zhang** [comment]
Sorry, when the paper public, CARLA don't have leaderboard 2.0, if you want, you can try to adapt this one to 2.0 version. And welcome to pull request.
