### ISSUE TITLE
out of lane

### ISSUE THREAD

**Issue by raozhongyu** [Kin-Zhang/mmfn#18]
你好，我根据您的代码尝试收集Vector map数据，但是显示out of lane，实际的map.png显示在车道线上，vector得到的值也为0，想问下您有什么好的建议吗

**Comment by Kin-Zhang** [comment]
这种情况可能是 town的OpenDrive信息缺失；你能说一下是Town几吗？我运行看一下

**Comment by raozhongyu** [comment]
目前测试的是Town02



发自我的iPhone


------------------ Original ------------------
From: Qingwen Zhang ***@***.***&gt;
Date: Wed,Feb 21,2024 5:01 PM
To: Kin-Zhang/mmfn ***@***.***&gt;
Cc: raozhongyu ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Kin-Zhang/mmfn] out of lane (Issue #18)





 
这种情况可能是 town的OpenDrive信息缺失；你能说一下是Town几吗？我运行看一下

**Comment by Kin-Zhang** [comment]
你可以先试其他的town 或者是下载pretrain weight... 我粗略用之前的电脑看了一眼 确实Town02是存在这个warning的 但其他的Town的收集是正常的；所以可能得看看之间有什么不同才能判断,我最近可能无法完成这个检查，如果你深入发现了 欢迎提pull request 告诉我

不过即使这个Town02 会出现在这个warning 数据还是可以用于训练的，整体上缺失一点也能使模型更鲁棒

**Comment by raozhongyu** [comment]
好的，谢谢，我尝试一下
