### ISSUE TITLE
eval

### ISSUE THREAD

**Issue by forlornLT** [Kin-Zhang/mmfn#2]
首先感谢您的贡献，这项工作也非常有趣！然后我想咨询一下您evaluate部分的代码好像和论文所述不太符合，请问有原版的代码吗，十分感谢！

**Comment by Kin-Zhang** [comment]
你是说论文中的两张大表吗？还是哪个评估部分？

**Comment by forlornLT** [comment]
就是从leaderboard_evaluator开始到自车_get_control()部分

**Comment by Kin-Zhang** [comment]
是expert还是e2e agent？没太听懂你说的哪个部分？

**Comment by forlornLT** [comment]
是e2e agent通关环境获取动作的部分，具体定位就是auto_pilot.py里的_get_control()

**Comment by Kin-Zhang** [comment]
auto_pilot是expert， 文件夹名字指明了

**Comment by Kin-Zhang** [comment]
论文里我对比了两个expert 和其各自收集的数据训练出的端到端agent，
其中expert对比是由mmfn_pilot and auto_pilot进行的，你问的应该是我的expert设计 应该看https://github.com/Kin-Zhang/mmfn/blob/main/team_code/expert_agent/mmfn_pilot.py 这个文件

---

当然论文是三月前完成的，后续有其他的开源项目 transfuser 那边的SEED，我还专门做了一个expert专场：https://github.com/Kin-Zhang/carla-expert

**Comment by forlornLT** [comment]
哦哦实在不好意思，看到了，应该是读的时候出现了纰漏，非常感谢您
