### ISSUE TITLE
请问如何修改测试时的视角

### ISSUE THREAD

**Issue by 23021211573** [Kin-Zhang/mmfn#20]
感谢您的工作，我希望测试时可以显示主驾驶视角或者车前视角，请问我该如何实现。万分感谢。

**Comment by 23021211573** [comment]
视角问题以解决，请问我怎么才能知道最后测试时模型的帧率？万分感谢

**Comment by Kin-Zhang** [comment]
我记得leaderboard的output会有帧率 但是涵盖了仿真的时间，如果你想要测量 model 推理的时间，加一个timer就行 time.time() 或者是：https://github.com/KTH-RPL/dztimer
