### ISSUE TITLE
AttributeError: 'LeaderboardEvaluator' object has no attribute 'manager'

### ISSUE THREAD

**Issue by sidg2110** [Kin-Zhang/mmfn#23]
I am trying to run the data collection python file.
In the `collect.yaml` file, I have set the configuration to - 
![Screenshot 2024-09-28 155406](https://github.com/user-attachments/assets/bc4fb6e2-ccb9-49c0-ae0d-c66bd5a47fa4)

I run the command - `python run_steps/phase0_run_eval.py port=2010 resume=True if_open_carla=True`

I get the following error - 
![image](https://github.com/user-attachments/assets/ad4d737b-484e-466b-9bc9-79197def8199)

How to resolve this error? I am using CARLA_0.9.10

**Comment by Kin-Zhang** [comment]
is CARLA open correctly by the scripts?

**Comment by sidg2110** [comment]
Resolved now. I think the issue was with in the `_cleanup()` method of `LeaderboardEvaluator` class. I added a `hasattr` check before deleting the `manager` object and it works fine now.
