### ISSUE TITLE
About the bias behind the generated dataset using Leaderboard routes

### ISSUE THREAD

**Issue by Dragonzz27** [Kin-Zhang/mmfn#24]
Much appreciation for your excellent work.

When I try to generate the dataset used for training network, I wonder whether  the quality of the generated dataset would influence the performance of the training process. 

So, is it necessary to generate dataset using the same routes multiple times and pick out the best dataset to minimize the bias behind the generating process of datasets.

By the way, how to quantify the quality of the generated dataset and did you take this problem into consideration.

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Kin-Zhang** [comment]
> I wonder whether the quality of the generated dataset would influence the performance of the training process.

I think it's hard to tell how to evaluate the quality of the generated dataset, if you mean the score of the expert, yes we have a table report in the paper, how the expert performance will influence the e2e agent.

Otherwise, I think you need define what quality mean to you.

> is it necessary to generate dataset using the same routes multiple times

Actually, they will have random weather condition even for the same routes, I think it's still worth to do it, but it also depends on your requirement like if you only want to a quick test or sota in the leaderboard.

**Comment by Dragonzz27** [comment]
> > I wonder whether the quality of the generated dataset would influence the performance of the training process.
> 
> I think it's hard to tell how to evaluate the quality of the generated dataset, if you mean the score of the expert, yes we have a table report in the paper, how the expert performance will influence the e2e agent.
> 
> Otherwise, I think you need define what quality mean to you.
> 
> > is it necessary to generate dataset using the same routes multiple times
> 
> Actually, they will have random weather condition even for the same routes, I think it's still worth to do it, but it also depends on your requirement like if you only want to a quick test or sota in the leaderboard.

Thanks for your answer for my questions, to evaluate such a huge dataset is quite complex.

Compared with other tasks in the process of building ego vehicles, maybe the bias of datasets is not important.
