### ISSUE TITLE
'RouteScenario' object has no attribute 'other_actors'

### ISSUE THREAD

**Issue by sidg2110** [Kin-Zhang/mmfn#25]
I am collecting data for short routes for towns using `phase0_run_eval.py`. I am seeing the below error while collecting data for short towns - 
```
The scenario could not be loaded:
> 'NoneType' object has no attribute 'try_spawn_actor'
Traceback (most recent call last):
  File "/DATA/btp/mmfn/leaderboard/leaderboard/leaderboard_evaluator.py", line 354, in _load_and_run_scenario
    scenario = RouteScenario(world=self.world, config=config, debug_mode=args.debug)
  File "/DATA/btp/mmfn/leaderboard/leaderboard/scenarios/route_scenario.py", line 191, in __init__
    ego_vehicle = self._update_ego_vehicle()
  File "/DATA/btp/mmfn/leaderboard/leaderboard/scenarios/route_scenario.py", line 251, in _update_ego_vehicle
    rolename='hero')
  File "/DATA/btp/mmfn/scenario_runner/srunner/scenariomanager/carla_data_provider.py", line 529, in request_new_actor
    actor = CarlaDataProvider._world.try_spawn_actor(blueprint, spawn_point)
AttributeError: 'NoneType' object has no attribute 'try_spawn_actor'
> Registering the route statistics
Exception ignored in: <function RouteScenario._del_ at 0x7f71e6b6f5f0>
Traceback (most recent call last):
  File "/DATA/btp/mmfn/leaderboard/leaderboard/scenarios/route_scenario.py", line 567, in __del__
    self.remove_all_actors()
  File "/DATA/btp/mmfn/scenario_runner/srunner/scenarios/basic_scenario.py", line 282, in remove_all_actors
    for i, _ in enumerate(self.other_actors):
AttributeError: 'RouteScenario' object has no attribute 'other_actors'
```

This error is coming up for some other towns as well but only for short routes. Data is collected for tiny routes without any error.

Any idea why this is coming up and how to fix it?

**Comment by Kin-Zhang** [comment]
I think it need more detail, which code commit you are running for leaderboard, roadrunner from caral/fork from me. and CARLA version, whether it open successfully, which towns you are mentioned, how could I reproduce this error. (Since I didn't have this err when I run it 4 years ago

**Comment by sidg2110** [comment]
I am using `mmfn_pilot` as the expert agent to collect the data after forking this repository. I am using CARLA 0.9.10. CARLA is opening successfully and even collecting the data successfully for tiny routes (eg. `routes_town03_tiny`).

The issue is showing up while collecting data for short routes of Town-3, 4, 5, 6, 10.

I did change anything from the repository code to collect the data. I think you should be able to reproduce the error by running the data collection script following the instructions you gave in README

**Comment by sidg2110** [comment]
I think the issue is in CARLA Leaderboard code rather than your code. Did you fix anything in there while working on this project?

**Comment by sidg2110** [comment]
Resolved. It was an error from my side.
