### ISSUE TITLE
Ask for training data？

### ISSUE THREAD

**Issue by HelloWorld416** [Kin-Zhang/mmfn#5]
十分有幸能读到您的这篇论文，同时也是个非常不错的工作。我想请问一下作者是否有这个打算将数据集公开？因为实验硬件的限制，生成自己的数据集有一定的困难。

**Comment by Kin-Zhang** [comment]
如果只是想尝试 训练过程，建议只收集一点点数据就可运行 训练进行调试查看 无需整体数据集（因为如果生成有困难 那么对应的这种训练也会较为困难；建议小设备可以仅仅尝试小数据收集和训练

抱歉 我这边没有合适的网盘/share 的地方进行提供这190G的数据，如果一定需要的话建议看看LAV的工作 他们提供了更多的数据 490G

**Comment by HelloWorld416** [comment]
了解了，非常感谢！

**Comment by Kin-Zhang** [comment]
根据其他人的请求，我上传了 我能找到的一些test的pretrained weight 如果需要 可以看一下此commit： https://github.com/Kin-Zhang/mmfn/commit/39b5a5fb40fd5298eb5cdf18b3f75aed37cf3ee8
