### ISSUE TITLE
Vulkan and OpenGL problem.

### ISSUE THREAD

**Issue by JianLiMech** [Kin-Zhang/mmfn#7]
Hello Ms.Zhang,

Thanks for your great work, your work is very important to me! I would like to use your work as baseline of my work. But I have a problem when I tried to run your work, it would be a great help if you could help me with this problem! 

Here are the details:
I tried to run CarlaUE4.sh on my local machine, it works but the machine gets so slow because the GPU is not good enugh (Nvidia 1030). So I decided to run it on a server with 4 2080Ti cards of my Institute. But the problem is I cannot run CarlaUE4.sh on the serve.  
The Error was  
![Screenshot from 2022-12-02 15-49-00](https://user-images.githubusercontent.com/105591726/206742518-d94f97fb-27ee-42f9-9a85-76a94fa1b3b4.png)
and 
![Screenshot from 2022-12-02 15-49-23](https://user-images.githubusercontent.com/105591726/206742727-d59e7d56-054e-403a-9fae-d32beb886238.png)

Does it mean we need to upgrade our graphic card driver or we need to configure something so I can run Carla on server?
Looking forward to see your response!

**Comment by Kin-Zhang** [comment]
b站回复了：
server跑的话 很多可能无法跑显示的 我之前也遇到过：建议 如果要跑CARLA还是在自己电脑上跑，然后收集完数据后传到server进行训练；虽然也有办法：https://blog.csdn.net/qq_39537898/article/details/122557353，但是我并不建议... 在server上尝试，如果你要尝试记得检查一下 下雨天的数据是否正常 就是图片是正常的显示还是都是黑点

English version: Click the right button and translate the whole page to English.
