### ISSUE TITLE
Please install the lib through readme, there will not vector map saved!

### ISSUE THREAD

**Issue by TU2021** [Kin-Zhang/mmfn#8]
张学姐你好，我是一个初入自动驾驶的小萌新研究生。在按照readme进行环境配置后，收集专家数据集时 vector map 无法收集到，尝试了一些修改都没有成功。请学姐多指教！

======== Preparing RouteScenario_1 (repetition 0) =========
> Setting up the agent
Data save path /home/drl/TU2023/mmfn/data/nss_0702/Town02_tiny/Town02_1_02_13_17_31_12
> Loading the world
> Running the route
Loading success for map, save path is: /home/drl/TU2023/mmfn/data/nss_0702/Town02_tiny/Town02_1_02_13_17_31_12
start to build rmap. map_number: 1
Please install the lib through readme, there will not vector map saved!

**Comment by Kin-Zhang** [comment]
在代码文件夹里 运行一下：
```bash
chmod +x scripts/*
./scripts/setup_lib.sh
```

安装一下库

**Comment by TU2021** [comment]
库已经全部安装了。本机的ubuntu版本是22.04，回溯了一下代码发现是assets/package中没有rough_map_node文件所以报错。但是看readme里面的data结构里面并没有vector map的部分，根据论文的意思是BEV和vector map的数据在训练的时候选择一种，难道收集也是二选一的吗？或者有无可能存在ubuntu版本问题，在docker里运行是否可行呢？

**Comment by Kin-Zhang** [comment]
奥 那我知道了 因为我当时只放了 三个版本的lib 16.04, 18.04, 20.04；可以用Docker 注意ubuntu版本就行

[Dockerfile](https://github.com/Kin-Zhang/mmfn/blob/main/Dockerfile) 

---

收集可以二选一 但是如果后面又要训练vector的话 就得重新收集，所以最好还是都收集；如果你不测vector的版本 就不用了

**Comment by TU2021** [comment]
谢谢。是否有机会能提供22.04版本的lib？您的这三个lib的来源是何处呢？

**Comment by Kin-Zhang** [comment]
Reference README.md:
Download the vectorized lib with .so, will install based on your system version, for commercial reason, we cannot open this part of codes(C++) fully but give the lib file

**Comment by TU2021** [comment]
emm，不太明白，意思是无法取得是吗？

**Comment by Kin-Zhang** [comment]
是的 这部分由于许可证原因 不能公开
